name: CD Pipeline - Frontend

on:
  workflow_run:
    workflows: ["CI Pipeline - Frontend"]
    types:
      - completed

jobs:
  web-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'production' }}
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: SSH to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH=~/.nvm/versions/node/v22.3.0/bin:$PATH
            cd /var/www/pso-fp-frontend
            git stash
            git checkout production
            git pull --rebase origin production
            yarn install
            yarn run build
            pm2 restart pso-frontend
            systemctl restart nginx