name: CI Pipeline - Frontend
on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run tests with coverage
        run: yarn test

      # - name: Normalize lcov path for SonarCloud
      #   run: |
      #     sed -i 's|\\|/|g' coverage/lcov.info

      - name: List coverage files
        run: ls -lah coverage/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.qualitygate.wait=true

      # - name: Build frontend
      #   run: yarn build
